# Generated by Django 4.2.16 on 2024-09-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=6)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('expire_time', models.DateTimeField()),
            ],
        ),
    ]
